### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by yc1999** [shenzaimin/CCKS2020Task4-3rd#1]
你好，在您的readme.md中写道：
```
1.执行分类模型：
训练集数据路径：code/CCKS-Cls/dataset/trans_train.json 测试集数据路径：code/CCKS-Cls/dataset/trans_test.json

cd /code/CCKS-Cls/ sh classification.sh 得到分类结果文件:/code/CCKS-Cls/test_output/cls_out_single.csv

说明：chinese_roberta_wwm_large_ext_pytorch 预训练模型文件路径 code/CCKS-Cls/pretrained_model/Bert-wwm-ext/ 下载链接： http://pan.iflytek.com/#/link/9B46A0ABA70C568AAAFCD004B9A2C773 提取密码：43eH
```
但是您的repository中并没有`CCKS-Cls`文件夹，请问能上传一下吗？谢谢。

**Comment by shenzaimin** [comment]
> 你好，在您的readme.md中写道：
> 
> ```
> 1.执行分类模型：
> 训练集数据路径：code/CCKS-Cls/dataset/trans_train.json 测试集数据路径：code/CCKS-Cls/dataset/trans_test.json
> 
> cd /code/CCKS-Cls/ sh classification.sh 得到分类结果文件:/code/CCKS-Cls/test_output/cls_out_single.csv
> 
> 说明：chinese_roberta_wwm_large_ext_pytorch 预训练模型文件路径 code/CCKS-Cls/pretrained_model/Bert-wwm-ext/ 下载链接： http://pan.iflytek.com/#/link/9B46A0ABA70C568AAAFCD004B9A2C773 提取密码：43eH
> ```
> 
> 但是您的repository中并没有`CCKS-Cls`文件夹，请问能上传一下吗？谢谢。

分类模块已经上传

**Comment by yc1999** [comment]
> > 你好，在您的readme.md中写道：
> > ```
> > 1.执行分类模型：
> > 训练集数据路径：code/CCKS-Cls/dataset/trans_train.json 测试集数据路径：code/CCKS-Cls/dataset/trans_test.json
> > 
> > cd /code/CCKS-Cls/ sh classification.sh 得到分类结果文件:/code/CCKS-Cls/test_output/cls_out_single.csv
> > 
> > 说明：chinese_roberta_wwm_large_ext_pytorch 预训练模型文件路径 code/CCKS-Cls/pretrained_model/Bert-wwm-ext/ 下载链接： http://pan.iflytek.com/#/link/9B46A0ABA70C568AAAFCD004B9A2C773 提取密码：43eH
> > ```
> > 
> > 
> > 但是您的repository中并没有`CCKS-Cls`文件夹，请问能上传一下吗？谢谢。
> 
> 分类模块已经上传

感谢🙇
